version: '3'

services:
  dbextensao:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${EXT_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${EXT_MYSQL_USER}
      - MYSQL_PASSWORD=${EXT_MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${EXT_MYSQL_HOST}
      - MYSQL_DATABASE=${EXT_MYSQL_USER}
    volumes:
      - ./logs:/var/log/mysql:rw
      - ./data:/var/lib/mysql:rw
  
  cad-pessoas-extensao:
    image: cad-pessoas-extensao
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_USER_NAME=${APP_USER_NAME}
        - APP_GID=${APP_UID}
        - APP_UID=${APP_GID}
    labels:
      - "traefik.enable=true"
      - "traefik.constraint-label-stack=cad-pessoas-extensao"
      - "traefik.docker.network=backend"
      - "traefik.http.services.cad-pessoas-extensao.loadbalancer.server.port=8000"
      #http
      - "traefik.http.routers.cad-pessoas-extensao_http.rule=Host(`extensao.${PRIMARY_DOMAIN_NAME}`)&&PathPrefix(`/`)"
      - "traefik.http.routers.cad-pessoas-extensao_http.entrypoints=web"
      - "traefik.http.routers.cad-pessoas-extensao_http.middlewares=https_redirect"
      #https
      - "traefik.http.routers.cad-pessoas-extensao_https.rule=Host(`extensao.${PRIMARY_DOMAIN_NAME}`)&&PathPrefix(`/`)"
      - "traefik.http.routers.cad-pessoas-extensao_https.entrypoints=websecure"
      - "traefik.http.routers.cad-pessoas-extensao_https.tls.certresolver=letsencryptresolver"
    depends_on:
      - dbextensao
    environment:
      - TZ:"America/Sao_Paulo"
      - NODE_ENV=production
      - TOPIC=putProtocolo
      - ENG_REST_URL=${CAMUNDA_URL}
      - ENG_REST_USERNAME=${CAMUNDA_USERNAME}
      - ENG_REST_PASSWORD=${CAMUNDA_PASSWORD}
      - MAX_TASK_DURATION=30000
      - DEV_SSH_HOST_NAME=${DEV_SSH_HOST_NAME}
      - DEV_SSH_HOST_USER=${DEV_SSH_HOST_USER}
      - DEV_SSH_HOST_PASS=${DEV_SSH_HOST_PASS}
      - SITES_SSH_HOST_NAME=${SITES_SSH_HOST_NAME}
      - SITES_SSH_HOST_USER=${SITES_SSH_HOST_USER}
      - SITES_SSH_HOST_PASS=${SITES_SSH_HOST_PASS}
      - SIGA-SER_SSH_HOST_NAME=${SIGA-SER_SSH_HOST_NAME}
      - SIGA-SER_SSH_HOST_USER=${SIGA-SER_SSH_HOST_USER}
      - SIGA-SER_SSH_HOST_PASS=${SIGA-SER_SSH_HOST_PASS}
      - PROTO_API_KEY=${PROTO_API_KEY}
      - PROTO_API_SECRET=${PROTO_API_SECRET}
      - PROTO_API_URL=${PROTO_API_URL}
      - MYSQL_ROOT_PASSWORD=${EXT_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${EXT_MYSQL_USER}
      - MYSQL_PASSWORD=${EXT_MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${EXT_MYSQL_HOST}
      - MYSQL_DATABASE=${EXT_MYSQL_USER}
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - AUTH_URL=${AUTH_URL}
      - ALFRESCO_BASE_URL=${ALFRESCO_BASE_URL}
      - ALFRESCO_USERNAME=${ALFRESCO_USERNAME}
      - ALFRESCO_PASSWORD=${ALFRESCO_PASSWORD}
      - ALFRESCO_ROOT_FOLDER_ID=${ALFRESCO_ROOT_FOLDER_ID}
      - SMTP_EXT_SERVER=${SMTP_EXT_SERVER}
      - SMTP_EXT_PORT=${SMTP_EXT_PORT}
      - MAIL_EXT_ACCOUNT=${MAIL_EXT_ACCOUNT}
      - MAIL_EXT_PASSWORD=${MAIL_EXT_PASSWORD}
      - MAIL_EXT_FROM=${MAIL_EXT_FROM}
      - EXT_BASE_URL=${EXT_BASE_URL}
      - EXT_DEV_BASE_URL=${EXT_DEV_BASE_URL}
      - EXT_DEV_USERNAME=${EXT_DEV_USERNAME}
      - EXT_DEV_PASSWORD=${EXT_DEV_PASSWORD}
      - EMAIL_COORDENADORA_EXT=${EMAIL_COORDENADORA_EXT}
      - EMAIL_GERENTE_EXT=${EMAIL_GERENTE_EXT}
    ports:
      - 8081:8000
    volumes:
      - ./app:/home/${APP_USER_NAME}
  
  celery:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=${APP_NAME}
        - APP_USER_NAME=${APP_USER_NAME}
        - APP_GID=${APP_UID}
        - APP_UID=${APP_GID}
    container_name: celery
    command: celery -A extensao worker --loglevel=INFO
    volumes:
      - ./app:/home/${APP_USER_NAME}
    depends_on:
      - redis
      - cad-pessoas-extensao
  
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./data:/data

networks:
  default:
    external: true
    name: backend
