version: '3.4'

services:
  cad-pessoas-extensao:
    image: cad-pessoas-extensao
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
        #    ports:
        #- 8000:8000
    volumes:
      - ./app:/home/appuser
    

networks:
   default:
     external: true
     name: backend
