version: '3.4'

services:
  cett_index:
    image: cett_index
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
     - 8000:8000
    volumes:
      - ./app:/home/appuser
    

networks:
   default:
     external: true
     name: backend
