# todo/todo_api/serializers.py
from rest_framework import serializers
from ..models.avaliacao import Avaliacao

class AvaliacaoSerializer(serializers.ModelSerializer):
    class Meta:
        model = Avaliacao
        fields = [
            "id",
            "nome",
            "endereco",
            "curso",
            "qtd_salas",
            "capacidade",
            "qtd_cadeiras",
            "qtd_tomadas",
            "qtd_janelas",
            "tipo_climatizacao",
            "qualidade_iluminacao",
            "turnos_disponiveis",
            "qtd_banheiros_masculino",
            "qtd_banheiros_feminino",
            "rede_eletrica",
            "qualidade_bebedouro",
            "acessibilidade",
            "internet",
            "data_show",
            "limpeza",
            "link_imagens",
            "parecer",
            "obs_parecer",
            "possui_cozinha",
            "capacidade_cozinha",
            "qtd_tomadas_cozinha",
            "funcionalidade_fogao",
            "refrigeracao",
            "gas",
            "bancadas_mesas",
            "capacidade_fornos",
            "qtd_fornos",
            "ventilacao_cozinha",
            "torneiras_funcionam",
            "area_complementar",
            "observacao_cozinha",
            "laboratorio_informatica",
            "qtd_computadores",
            "cabeamento_internet",
            "qtd_computadores_wifi",
            "obs_informatica",
            "lavatorio",
            "qtd_lavatorio_sb",
            "cadeiras_de_sb",
            "qtd_cadeiras_sb",
            "cidade",
            "obsinfra",
            "cidade_realizacao",
            "avalLocalEmailAvaliador",
            "tipoAvaliacao",
            "endereco_realizacao",
            "observacao_beleza",
            "sevicodebeleza",
            "confeitaria",
            "UsuariolAvaliador",
            "avalLocalNomeAvaliador",
            "infomatica",
        ]
