# Generated by Django 4.1.1 on 2022-09-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
