# Generated by Django 4.1.1 on 2022-09-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='observacao_cozinha',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='parecer',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='rede_eletrica',
            field=models.CharField(max_length=500),
        ),
    ]
