# Generated by Django 4.1.1 on 2022-10-04 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_endereco_evento_alocacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='endereco',
        ),
        migrations.DeleteModel(
            name='Alocacao',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
