# Generated by Django 4.1.1 on 2022-10-04 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_remove_evento_endereco_delete_alocacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('endereco_completo', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'enderecos',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(null=True)),
                ('data_fim', models.DateField(null=True)),
                ('observacao', models.CharField(max_length=500, null=True)),
                ('cidade', models.CharField(max_length=50, null=True)),
                ('enderecos', models.ManyToManyField(null=True, to='sistema.endereco')),
            ],
            options={
                'db_table': 'eventos',
            },
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(null=True)),
                ('data_fim', models.DateField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('observacao', models.CharField(max_length=500, null=True)),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.evento')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.pessoas')),
            ],
            options={
                'db_table': 'alocacoes',
            },
        ),
    ]
