# Generated by Django 4.1.1 on 2022-10-05 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_endereco_evento_alocacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'cidade',
            },
        ),
        migrations.RemoveField(
            model_name='evento',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='enderecos',
        ),
        migrations.AddField(
            model_name='evento',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.endereco'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.cidade'),
        ),
    ]
