# Generated by Django 4.1.1 on 2022-10-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_alter_evento_data_fim_alter_evento_data_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
    ]
