# Generated by Django 4.1.1 on 2022-10-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='sistema.curso'),
        ),
    ]
