# Generated by Django 4.1.2 on 2022-10-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_pessoas_cursos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoas',
            name='endereco',
        ),
        migrations.AddField(
            model_name='pessoas',
            name='bairro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='cidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='complemento',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='rua',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='acessibilidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='area_complementar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='bancadas_mesas',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='cabeamento_internet',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='cadeiras_de_sb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='capacidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='capacidade_cozinha',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='capacidade_fornos',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='cidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='curso',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='data_show',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='endereco',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='funcionalidade_fogao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='gas',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='internet',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='laboratorio_informatica',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='lavatorio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='limpeza',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='link_imagens',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='obs_informatica',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='observacao_cozinha',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='parecer',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='possui_cozinha',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='qtd_banheiros_feminino',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='qtd_banheiros_masculino',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='qtd_cadeiras',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='qtd_cadeiras_sb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='qtd_computadores',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='qtd_computadores_wifi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='qtd_fornos',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='qtd_janelas',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='qtd_lavatorio_sb',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='qtd_salas',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='qtd_tomadas',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='qtd_tomadas_cozinha',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='qualidade_bebedouro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='qualidade_iluminacao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='rede_eletrica',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='refrigeracao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='tipo_climatizacao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='torneiras_funcionam',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='turnos_disponiveis',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='ventilacao_cozinha',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='agencia',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='banco',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='cargo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='cep',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='conta',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='cpf',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='data_nascimento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='orgao_emissor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='pix',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='qtd_contratacoes',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='rg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='telefone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='tipo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='user_camunda',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
