# Generated by Django 4.1.2 on 2022-10-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0014_endereco_bairro_endereco_cep_endereco_complemento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='endereco_completo',
        ),
    ]
