# Generated by Django 4.1.2 on 2022-10-14 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0015_remove_endereco_endereco_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacao',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.curso'),
        ),
    ]
