# Generated by Django 4.1.2 on 2022-10-14 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0016_alocacao_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alocacao',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes', to='sistema.pessoas'),
        ),
    ]
