# Generated by Django 4.1.2 on 2022-10-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0018_alter_alocacao_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='data_emissao',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='estado',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='estado_civil',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='nome_mae',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='nome_pai',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='numero_endereco',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='pis_pasep',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='sexo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='telefone_recado',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='tipo_conta',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
