# Generated by Django 4.1.2 on 2022-10-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0020_alter_avaliacao_acessibilidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='UsuariolAvaliador',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avalLocalEmailAvaliador',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avalLocalNomeAvaliador',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='cidade_realizacao',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='confeitaria',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='endereco_realizacao',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='infomatica',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='observacao_beleza',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='obsinfra',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='sevicodebeleza',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='tipoAvaliacao',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
