# Generated by Django 4.1.2 on 2022-10-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0021_avaliacao_usuariolavaliador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='obs_parecer',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
