# Generated by Django 4.1.2 on 2022-10-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0022_avaliacao_obs_parecer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='id_protocolo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
