# Generated by Django 4.1.3 on 2022-11-18 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0024_escola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='endereco',
        ),
        migrations.AddField(
            model_name='escola',
            name='bairro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='cep',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.cidade'),
        ),
        migrations.AddField(
            model_name='escola',
            name='complemento',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='logradouro',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
