# Generated by Django 4.1.3 on 2022-11-21 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0026_evento_bairro_evento_cep_evento_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacao',
            name='bairro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='cep',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.cidade'),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='complemento',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='logradouro',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
