# Generated by Django 4.1.3 on 2022-11-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0027_alocacao_bairro_alocacao_cep_alocacao_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, null=True)),
                ('carga_horaria', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'turno',
            },
        ),
        migrations.AddField(
            model_name='alocacao',
            name='turno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.turno'),
        ),
    ]
