# Generated by Django 4.1.3 on 2022-11-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0028_turno_alocacao_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alocacao',
            name='turno',
        ),
        migrations.AddField(
            model_name='alocacao',
            name='turno',
            field=models.ManyToManyField(blank=True, to='sistema.turno'),
        ),
    ]
