# Generated by Django 4.1.3 on 2022-11-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0029_remove_alocacao_turno_alocacao_turno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alocacao',
            old_name='turno',
            new_name='turnos',
        ),
    ]
