# Generated by Django 4.1.3 on 2022-11-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0030_rename_turno_alocacao_turnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacao',
            name='aulas_sabado',
            field=models.BooleanField(default=False),
        ),
    ]
