# Generated by Django 4.1.3 on 2022-12-01 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0031_alocacao_aulas_sabado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='escola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.escola'),
        ),
    ]
