# Generated by Django 4.1.4 on 2022-12-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0032_evento_escola'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50, null=True)),
                ('process_instance', models.FloatField(null=True)),
                ('variaveis', models.JSONField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'demandas',
            },
        ),
    ]
