# Generated by Django 4.1.4 on 2022-12-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0033_demanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='descricao',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
