# Generated by Django 4.1.4 on 2022-12-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0034_demanda_descricao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demanda',
            new_name='Acao',
        ),
        migrations.AlterModelTable(
            name='acao',
            table='acoes',
        ),
    ]
