# Generated by Django 4.1.4 on 2022-12-07 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0035_rename_demanda_acao_alter_acao_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='bairro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='acao',
            name='cep',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='acao',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.cidade'),
        ),
        migrations.AddField(
            model_name='acao',
            name='complemento',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='acao',
            name='data_fim',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='acao',
            name='data_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='acao',
            name='logradouro',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
