# Generated by Django 4.1.4 on 2022-12-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0038_membroexecucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='membrosDeExecucao',
            field=models.ManyToManyField(blank=True, through='sistema.MembroExecucao', to='sistema.pessoas'),
        ),
    ]
