# Generated by Django 4.1.4 on 2022-12-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0039_acao_membrosdeexecucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroexecucao',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
