# Generated by Django 4.1.4 on 2022-12-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0040_membroexecucao_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acao',
            old_name='membrosDeExecucao',
            new_name='membrosExecucao',
        ),
    ]
