# Generated by Django 4.1.4 on 2022-12-15 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0041_rename_membrosdeexecucao_acao_membrosexecucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='escola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.escola'),
        ),
    ]
