# Generated by Django 4.1.4 on 2022-12-19 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0043_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='membro_execucao',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.membroexecucao'),
        ),
    ]
