# Generated by Django 4.1.4 on 2023-01-06 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0044_alter_ticket_membro_execucao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'itinerario',
            },
        ),
        migrations.CreateModel(
            name='ItinerarioItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateField(blank=True, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=250, null=True)),
                ('cep', models.CharField(blank=True, max_length=100, null=True)),
                ('complemento', models.CharField(blank=True, max_length=250, null=True)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.cidade')),
                ('escola', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.escola')),
            ],
            options={
                'db_table': 'itinerario_itens',
            },
        ),
    ]
