# Generated by Django 4.1.4 on 2023-01-06 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0045_itinerario_itinerarioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarioitem',
            name='itinerario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.itinerario'),
        ),
        migrations.AddField(
            model_name='membroexecucao',
            name='itinerario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.itinerario'),
        ),
    ]
