# Generated by Django 4.1.4 on 2023-01-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0046_itinerarioitem_itinerario_membroexecucao_itinerario'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarioitem',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itinerarioitem',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
