# Generated by Django 4.1.4 on 2023-01-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0047_itinerarioitem_latitude_itinerarioitem_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarioitem',
            name='data_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
