# Generated by Django 4.1.4 on 2023-01-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0048_alter_itinerarioitem_data_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarioitem',
            name='endereco',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
