# Generated by Django 4.1.4 on 2023-01-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0049_itinerarioitem_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerario',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
