# Generated by Django 4.1.4 on 2023-01-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0050_itinerario_color'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='itinerario',
            table='itinerarios',
        ),
    ]
