# Generated by Django 4.1.5 on 2023-01-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0053_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='linkDocumentos',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
