# Generated by Django 4.1.5 on 2023-01-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0054_atividade_linkdocumentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasRemovidas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'datas_removidas',
            },
        ),
    ]
