# Generated by Django 4.1.5 on 2023-01-25 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0055_datasremovidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasremovidas',
            name='alocacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.alocacao'),
        ),
    ]
