# Generated by Django 4.1.5 on 2023-01-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0056_datasremovidas_alocacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatasRemovidas',
            new_name='DataRemovida',
        ),
    ]
