# Generated by Django 4.1.5 on 2023-01-26 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0057_rename_datasremovidas_dataremovida'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evento',
            table='ensino',
        ),
    ]
