# Generated by Django 4.1.5 on 2023-01-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0058_alter_evento_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Evento',
            new_name='Ensino',
        ),
    ]
