# Generated by Django 4.1.5 on 2023-01-27 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0059_rename_evento_ensino'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpEvento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('process_instance', models.CharField(blank=True, max_length=300, null=True)),
                ('variaveis', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.CharField(blank=True, max_length=1000, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=250, null=True)),
                ('cep', models.CharField(blank=True, max_length=100, null=True)),
                ('complemento', models.CharField(blank=True, max_length=250, null=True)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.cidade')),
                ('escola', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.escola')),
            ],
            options={
                'db_table': 'dp_eventos',
            },
        ),
    ]
