# Generated by Django 4.1.5 on 2023-01-27 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0060_dpevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroexecucao',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.dpevento'),
        ),
    ]
