# Generated by Django 4.1.5 on 2023-01-30 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0061_membroexecucao_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.dpevento'),
        ),
    ]
