# Generated by Django 4.1.5 on 2023-02-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0066_ensino_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensino',
            name='process_instance',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
