# Generated by Django 4.1.5 on 2023-02-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0067_ensino_process_instance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alocacao',
            old_name='evento',
            new_name='acaoEnsino',
        ),
    ]
