# Generated by Django 4.1.6 on 2023-02-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0068_rename_evento_alocacao_acaoensino'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroexecucao',
            name='avaliador',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
