# Generated by Django 4.1.6 on 2023-02-15 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0070_pessoas_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='cidade',
        ),
        migrations.AddField(
            model_name='atividade',
            name='cargaHoraria',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='quantidadeAtendimentos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='quantidadeCertificacoes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='quantidadeInscricoes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='quantidadeMatriculas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='acao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.acao'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.membroexecucao'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='cep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='complemento',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.dpevento'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='logradouro',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dpevento',
            name='acaoEnsino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.ensino'),
        ),
    ]
