# Generated by Django 4.1.6 on 2023-02-10 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0071_avaliacao_acao_avaliacao_avaliador_avaliacao_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.membroexecucao'),
        ),
    ]
