# Generated by Django 4.1.6 on 2023-02-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0072_alter_avaliacao_avaliador'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='cargaHoraria',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='quantidadeAtendimentos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='quantidadeCertificacoes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='quantidadeInscricoes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='quantidadeMatriculas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
