# Generated by Django 4.1.7 on 2023-02-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0072_remove_avaliacao_usuariolavaliador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoatividade',
            name='descricao',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
