# Generated by Django 4.1.6 on 2023-02-14 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0073_atividade_cargahoraria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpevento',
            name='acaoEnsino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.ensino'),
        ),
    ]
