# Generated by Django 4.1.7 on 2023-02-24 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0073_alter_tipoatividade_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
                ('quantidadeAtendimentos', models.IntegerField(blank=True, null=True)),
                ('quantidadeVendas', models.IntegerField(blank=True, null=True)),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.atividade')),
            ],
            options={
                'db_table': 'servicos',
            },
        ),
    ]
