# Generated by Django 4.1.7 on 2023-02-24 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0074_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='bairro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='cep',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.cidade'),
        ),
        migrations.AddField(
            model_name='servico',
            name='complemento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='logradouro',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
