# Generated by Django 4.1.7 on 2023-03-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0075_servico_bairro_servico_cep_servico_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='qtdSalas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
