# Generated by Django 4.1.7 on 2023-03-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0077_avaliacao_observacaogeral'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='observacaoGeralUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='qtdSalasUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
