# Generated by Django 4.1.7 on 2023-03-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0078_avaliacao_observacaogeralupdatedat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='geralHasBebedouro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='geralHasBebedouroUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='geralHasCadeiras',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='geralHasCadeirasUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='geralHasEquipeLimpeza',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='geralHasEquipeLimpezaUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='geralHasIluminacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='geralHasIluminacaoUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='geralHasRedeEletrica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='geralHasRedeEletricaUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='geralQuantidadeBanheiros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='geralQuantidadeBanheirosUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='geralQuantidadeDataShow',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='geralQuantidadeDataShowUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='geralQuantidadeJanelas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='geralQuantidadeJanelasUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='geralTamanhoEspaco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='geralTamanhoEspacoUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaHasEspacoTurmas40Alunos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaHasEspacoTurmas40AlunosUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaHasIluminacaoAdequada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaHasIluminacaoAdequadaUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaHasVentilacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaHasVentilacaoUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaObservacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaObservacaoUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaQuantidadeFogoesFuncionando',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaQuantidadeFogoesFuncionandoUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaQuantidadeFornosFuncionando',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaQuantidadeFornosFuncionandoUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaQuantidadeGeladeirasFuncionando',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaQuantidadeGeladeirasFuncionandoUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaQuantidadeMesasBancadas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaQuantidadeMesasBancadasUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaQuantidadePiasComTorneiraFuncionando',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaQuantidadePiasComTorneiraFuncionandoUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaQuantidadeTomadas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaQuantidadeTomadasUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaQuantidadeVasilhamesGasComGas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaQuantidadeVasilhamesGasComGasUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaQuantidadeVasilhamesGasVazios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaCulinariaQuantidadeVasilhamesGasVaziosUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaServicosBelezaHasPontoAguaExterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaServicosBelezaHasPontoAguaExternoUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaServicosBelezaObservacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaServicosBelezaObservacaoUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaServicosBelezaQuantidadeCadeirasSalao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaServicosBelezaQuantidadeCadeirasSalaoUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaServicosBelezaQuantidadePiasHigienizacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='salaServicosBelezaQuantidadePiasHigienizacaoUpdatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
