# Generated by Django 4.1.7 on 2023-03-27 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0079_avaliacao_geralhasbebedouro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='membro_execucao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.membroexecucao'),
        ),
    ]
