# Generated by Django 4.1.7 on 2023-03-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0081_membroexecucao_observacao_ticket_bairro_ticket_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='observacao',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
