# Generated by Django 4.1.7 on 2023-04-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0084_alocacao_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alocacao',
            name='tipo',
        ),
    ]
