# Generated by Django 4.1.7 on 2023-04-04 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0086_ticket_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='alocacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.alocacao'),
        ),
    ]
