# Generated by Django 4.1.7 on 2023-04-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0087_ticket_alocacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoContratado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descriicao', models.CharField(max_length=100, null=True)),
                ('valor', models.FloatField(max_length=100, null=True)),
                ('data_limite', models.DateField(null=True)),
            ],
            options={
                'db_table': 'servicos_contratados',
            },
        ),
    ]
