# Generated by Django 4.1.7 on 2023-04-12 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0088_servicocontratado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicocontratado',
            old_name='descriicao',
            new_name='descricao',
        ),
    ]
