# Generated by Django 4.1.7 on 2023-04-13 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0089_rename_descriicao_servicocontratado_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicocontratado',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.dpevento'),
        ),
    ]
