# Generated by Django 4.1.7 on 2023-04-13 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0090_servicocontratado_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicocontratado',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.membroexecucao'),
        ),
    ]
