# Generated by Django 4.1.7 on 2023-04-14 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0091_servicocontratado_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='servico_contratado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.servicocontratado'),
        ),
    ]
