# Generated by Django 4.1.7 on 2023-04-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0092_ticket_servico_contratado'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='id_protocolo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
