# Generated by Django 4.1.7 on 2023-04-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0093_atividade_id_protocolo_atividade_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='descricao',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
