# Generated by Django 4.2 on 2023-04-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0094_servico_descricao_servico_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'galerias',
            },
        ),
    ]
