# Generated by Django 4.2 on 2023-04-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0095_galeria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_alfresco', models.CharField(max_length=100, null=True)),
                ('descricao', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'imagens',
            },
        ),
    ]
