# Generated by Django 4.2 on 2023-04-17 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0096_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='galeria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.galeria'),
        ),
    ]
