# Generated by Django 4.2 on 2023-04-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0097_imagem_galeria'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlfrescoNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_file', models.BooleanField()),
                ('created_by_user_id', models.CharField(max_length=255)),
                ('created_by_user_display_name', models.CharField(max_length=255)),
                ('modified_at', models.DateTimeField()),
                ('node_type', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('mime_type_name', models.CharField(max_length=255)),
                ('size_in_bytes', models.PositiveIntegerField()),
                ('encoding', models.CharField(max_length=255)),
                ('parent_id', models.CharField(max_length=255)),
                ('aspect_names', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('is_folder', models.BooleanField()),
                ('modified_by_user_id', models.CharField(max_length=255)),
                ('modified_by_user_display_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('entry_id', models.CharField(max_length=255)),
                ('version_label', models.CharField(max_length=255)),
                ('version_type', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='imagem',
            name='shared_link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
