# Generated by Django 4.2 on 2023-04-18 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0098_alfresconode_imagem_shared_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.dpevento'),
        ),
    ]
