# Generated by Django 4.2 on 2023-04-25 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0099_galeria_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='galeria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.galeria'),
        ),
    ]
