# Generated by Django 4.2 on 2023-04-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0100_atividade_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='data_realizacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
