# Generated by Django 4.2 on 2023-04-27 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0101_atividade_data_realizacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividade',
            old_name='data_realizacao',
            new_name='data_realizacao_inicio',
        ),
    ]
