# Generated by Django 4.2 on 2023-04-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0102_rename_data_realizacao_atividade_data_realizacao_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='data_realizacao_fim',
            field=models.DateField(blank=True, null=True),
        ),
    ]
