# Generated by Django 4.2 on 2023-04-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0103_atividade_data_realizacao_fim'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensino',
            name='etapa',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
