# Generated by Django 4.2 on 2023-04-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0104_ensino_etapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacao',
            name='codigo_siga',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='quantidade_matriculas',
            field=models.IntegerField(null=True),
        ),
    ]
