# Generated by Django 4.2 on 2023-04-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0105_alocacao_codigo_siga_alocacao_quantidade_matriculas'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='atividade_meta',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
