# Generated by Django 4.2 on 2023-04-28 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0106_atividade_atividade_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.pessoas'),
        ),
    ]
