# Generated by Django 4.2 on 2023-05-02 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0107_ticket_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='escola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.escola'),
        ),
    ]
