# Generated by Django 4.2.1 on 2023-05-09 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0108_ticket_escola'),
    ]

    operations = [
        migrations.CreateModel(
            name='DpEventoEscola',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dp_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.dpevento')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.escola')),
            ],
            options={
                'db_table': 'dp_eventos_escolas',
            },
        ),
        migrations.AddField(
            model_name='dpevento',
            name='escolas',
            field=models.ManyToManyField(blank=True, related_name='escolas', through='sistema.DpEventoEscola', to='sistema.escola'),
        ),
    ]
