# Generated by Django 4.2.1 on 2023-05-10 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0109_dpeventoescola_dpevento_escolas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='atividade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.atividade'),
        ),
    ]
