# Generated by Django 4.2.1 on 2023-05-12 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0110_ticket_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.dpevento')),
            ],
            options={
                'db_table': 'secoes_atividades',
            },
        ),
    ]
