# Generated by Django 4.2.1 on 2023-05-12 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0111_atividadesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='atividadeSection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.atividadesection'),
        ),
    ]
