# Generated by Django 4.2.1 on 2023-05-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0113_atividade_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fonte', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.CharField(blank=True, max_length=300, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('id_model', models.IntegerField(blank=True, null=True)),
                ('id_alfresco', models.CharField(max_length=100, null=True)),
                ('shared_link', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'anexos',
            },
        ),
    ]
