# Generated by Django 4.2.1 on 2023-05-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0114_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
