# Generated by Django 4.2.1 on 2023-05-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0115_anexo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='nome',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
