# Generated by Django 4.2.1 on 2023-05-17 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0117_atividade_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='beneficiario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiario', to='sistema.pessoas'),
        ),
    ]
