# Generated by Django 4.2.1 on 2023-05-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0118_ticket_beneficiario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='valor_orcado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
