# Generated by Django 4.2.1 on 2023-05-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0119_ticket_valor_orcado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='valor_executado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
