# Generated by Django 4.2.1 on 2023-05-23 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0120_ticket_valor_executado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensino',
            name='anexo_oficio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.anexo'),
        ),
        migrations.AddField(
            model_name='ensino',
            name='numero_oficio',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
