# Generated by Django 4.2.1 on 2023-05-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0121_ensino_anexo_oficio_ensino_numero_oficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacao',
            name='data_retorno',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='data_saida',
            field=models.DateField(null=True),
        ),
    ]
