# Generated by Django 4.2.1 on 2023-05-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0122_alocacao_data_retorno_alocacao_data_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='nome',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
