# Generated by Django 4.2.1 on 2023-05-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0128_ticket_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensino',
            name='has_credito_social',
            field=models.BooleanField(default=False),
        ),
    ]
