# Generated by Django 4.2.1 on 2023-06-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0129_ensino_has_credito_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpevento',
            name='horarioFim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dpevento',
            name='horarioInicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
