# Generated by Django 4.2.1 on 2023-06-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0130_dpevento_horariofim_dpevento_horarioinicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpevento',
            name='edicao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
