# Generated by Django 4.2.1 on 2023-06-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0131_dpevento_edicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('badge', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'atividade_categorias',
            },
        ),
    ]
