# Generated by Django 4.2.1 on 2023-06-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0132_atividadecategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='atividadeCategorias',
            field=models.ManyToManyField(blank=True, null=True, to='sistema.atividadecategoria'),
        ),
    ]
