# Generated by Django 4.2.1 on 2023-06-05 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0135_alter_atividadecategoria_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='data_criacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitante', to='sistema.pessoas'),
        ),
    ]
