# Generated by Django 4.2.2 on 2023-06-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0136_ticket_data_criacao_ticket_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='id_siga',
            field=models.IntegerField(null=True),
        ),
    ]
