# Generated by Django 4.2.2 on 2023-07-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0138_alter_ensino_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
