# Generated by Django 4.2.3 on 2023-07-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0139_alter_atividade_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='instituicao',
            field=models.CharField(choices=[('escola', 'Escola'), ('cett', 'CETT'), ('outros', 'Outros')], default='escola', max_length=50),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
