# Generated by Django 4.2.3 on 2023-07-19 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0141_alter_pessoas_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.escola'),
        ),
    ]
