# Generated by Django 4.2.3 on 2023-07-20 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sistema', '0142_pessoas_escola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoa', to=settings.AUTH_USER_MODEL),
        ),
    ]
