# Generated by Django 4.2.3 on 2023-07-21 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0144_orcamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('unidade', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sistema.orcamento')),
            ],
            options={
                'db_table': 'orcamento_itens',
            },
        ),
    ]
