# Generated by Django 4.2.3 on 2023-07-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0145_orcamentoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropostaProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_projeto', models.CharField(blank=True, max_length=255, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('resumo_proposta', models.TextField(blank=True, null=True)),
                ('objetivos_gerais', models.TextField(blank=True, null=True)),
                ('objetivos_especificos', models.TextField(blank=True, null=True)),
                ('metodologia', models.TextField(blank=True, null=True)),
                ('formato_conteudo', models.TextField(blank=True, null=True)),
                ('justificativas', models.TextField(blank=True, null=True)),
                ('resultados_esperados', models.TextField(blank=True, null=True)),
                ('fontes_apoio', models.TextField(blank=True, null=True)),
                ('informacoes_adicionais', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'propostas_projeto',
            },
        ),
    ]
