# Generated by Django 4.2.3 on 2023-07-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0147_propostaprojeto_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='local',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='publico_esperado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
