# Generated by Django 4.2.3 on 2023-07-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0152_membroexecucao_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='horario_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atividade',
            name='horario_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
