# Generated by Django 4.2.3 on 2023-07-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0153_atividade_horario_fim_atividade_horario_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='horario_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
