# Generated by Django 4.2.3 on 2023-07-24 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0154_alter_atividade_horario_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membroexecucao',
            name='proposta_projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe', to='sistema.propostaprojeto'),
        ),
    ]
