# Generated by Django 4.2.3 on 2023-07-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0156_alter_atividade_proposta_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroexecucao',
            name='instituicao',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
