# Generated by Django 4.2.3 on 2023-07-27 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0159_propostaprojeto_publico_alvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostaprojeto',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='propostaprojeto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
