# Generated by Django 4.2.3 on 2023-07-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0160_propostaprojeto_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostaprojeto',
            name='status',
            field=models.CharField(choices=[('em_analise', 'Em análise'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada'), ('cancelada', 'Cancelada')], default='em_analise', max_length=255),
        ),
    ]
