# Generated by Django 4.2.3 on 2023-07-27 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0162_propostaprojeto_escola_alter_propostaprojeto_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conteudo', models.TextField(null=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to='sistema.pessoas')),
                ('proposta_projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to='sistema.propostaprojeto')),
            ],
            options={
                'db_table': 'comentarios',
            },
        ),
    ]
