# Generated by Django 4.2.3 on 2023-07-27 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0163_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
