# Generated by Django 4.2.3 on 2023-07-28 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0165_dpevento_proposta_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpevento',
            name='proposta_projeto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento', to='sistema.propostaprojeto'),
        ),
    ]
