# Generated by Django 4.2.4 on 2023-08-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0167_imagem_show_on_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoitem',
            name='em_estoque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='propostaprojeto',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('em_analise', 'Em análise'), ('devolvida', 'Devolvida'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada'), ('cancelada', 'Cancelada')], default='em_analise', max_length=255),
        ),
    ]
