# Generated by Django 4.2.4 on 2023-08-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0168_orcamentoitem_em_estoque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpevento',
            name='descricao',
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
    ]
