# Generated by Django 4.2.5 on 2023-09-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0169_alter_dpevento_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpevento',
            name='tipo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='propostaprojeto',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('em_analise', 'Em análise'), ('em_analise_direcao', 'Em análise pela direção'), ('em_analise_cett', 'Em análise pelo CETT'), ('devolvida', 'Devolvida'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada'), ('cancelada', 'Cancelada')], default='em_analise', max_length=255),
        ),
    ]
