# Generated by Django 4.2.5 on 2023-09-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0170_alter_dpevento_tipo_alter_propostaprojeto_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembroExecucaoRoles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'membro_execucao_roles',
            },
        ),
    ]
