# Generated by Django 4.2.5 on 2023-09-13 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0171_membroexecucaoroles'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroexecucao',
            name='role_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.membroexecucaoroles'),
        ),
    ]
