# Generated by Django 4.2.5 on 2023-09-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0174_remove_membroexecucao_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membroexecucao',
            old_name='role_model',
            new_name='role',
        ),
    ]
