# Generated by Django 4.2.5 on 2023-09-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0175_rename_role_model_membroexecucao_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='membroexecucao',
            name='roles',
            field=models.ManyToManyField(related_name='membros_execucao', to='sistema.membroexecucaoroles'),
        ),
    ]
