# Generated by Django 4.2.5 on 2023-09-13 19:46

from django.db import models, migrations

def forward(apps, schema_editor):
    MembroExecucao = apps.get_model("sistema", "MembroExecucao")
    for membro in MembroExecucao.objects.all():
        if membro.role:
            membro.roles.add(membro.role)

def reverse(apps, schema_editor):
    pass
class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0176_membroexecucao_roles'),
    ]

    operations = [
        migrations.RunPython(forward, reverse)
    ]