# Generated by Django 4.2.5 on 2023-09-14 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0177_auto_20230913_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacao',
            name='atividade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.atividade'),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='funcao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='horas_alocadas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='membroExecucao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.membroexecucao'),
        ),
    ]
