# Generated by Django 4.2.5 on 2023-09-15 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0178_alocacao_atividade_alocacao_funcao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alocacao',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='alocacao',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='alocacao',
            name='horas_alocadas',
        ),
        migrations.RemoveField(
            model_name='alocacao',
            name='membroExecucao',
        ),
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('unidade', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('em_estoque', models.BooleanField(default=False)),
                ('proposta_projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='sistema.propostaprojeto')),
            ],
            options={
                'db_table': 'recursos',
            },
        ),
    ]
