# Generated by Django 4.2.5 on 2023-09-15 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0179_remove_alocacao_atividade_remove_alocacao_funcao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursos',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.dpevento'),
        ),
    ]
