# Generated by Django 4.2.5 on 2023-09-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0182_auto_20230918_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='numero_matricula',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
