# Generated by Django 4.2.5 on 2023-09-18 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0183_pessoas_numero_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacao',
            name='atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.atividade'),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='cargaHoraria',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='funcao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alocacao',
            name='tipoContratacao',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
