# Generated by Django 4.2.5 on 2023-09-18 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0184_alocacao_atividade_alocacao_cargahoraria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacao',
            name='membroExecucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.membroexecucao'),
        ),
    ]
