# Generated by Django 4.2.5 on 2023-09-18 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0185_alocacao_membroexecucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alocacao',
            name='atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes', to='sistema.atividade'),
        ),
        migrations.AlterField(
            model_name='alocacao',
            name='membroExecucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes', to='sistema.membroexecucao'),
        ),
    ]
