# Generated by Django 4.2.5 on 2023-09-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0188_pessoas_tipo_contratacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='atividadeCategorias',
            field=models.ManyToManyField(blank=True, related_name='atividades', to='sistema.atividadecategoria'),
        ),
    ]
