# Generated by Django 4.2.5 on 2023-09-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0190_auto_20230930_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='tipo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
