# Generated by Django 4.2.6 on 2023-10-09 14:20

from django.db import migrations

def create_galerias_for_atividades(apps, schema_editor):
    Atividade = apps.get_model('sistema', 'Atividade')
    Galeria = apps.get_model('sistema', 'Galeria')
    
    for atividade in Atividade.objects.all():
        if atividade.galeria is None and atividade.evento is not None:
            Galeria.objects.create(
                nome=f'galeria atividade {atividade.id}',
                evento=atividade.evento,
            )

def rollback(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0192_propostaprojeto_formato_conteudo_tipo'),
    ]

    operations = [
        migrations.RunPython(create_galerias_for_atividades, rollback),
    ]
