from .cidade import Cidade
from .ensino import Ensino 
from .endereco import Endereco
from .alocacao import Alocacao
from .avaliacao import Avaliacao
from .pessoa import Pessoas
from .curso import Curso
from .escola import Escola
from .acao import Acao
from .ticket import Ticket
from .membroExecucao import MembroExecucao
from .itinerario import Itinerario
from .itinerarioItem import ItinerarioItem
from .tipoAtividade import TipoAtividade
from .atividade import Atividade
from .dataRemovida import DataRemovida
from .dpEvento import DpEvento
from .departamento import Departamento