from .cidade import Cidade
from .evento import Evento 
from .endereco import Endereco
from .alocacao import Alocacao
from .avaliacao import Avaliacao
from .pessoa import Pessoas
from .curso import Curso
from .escola import Escola
from .acao import Acao
from .ticket import Ticket
from .membroExecucao import MembroExecucao